require("core.plugin_config.nvim_tree")
require("core.plugin_config.onedarkpro")
require("core.plugin_config.lualine")
require("core.plugin_config.tree_sitter")
require("core.plugin_config.telescope")
